var white_goose = new Image();
white_goose.src = "/paint/white_goose_mini.png";

const out_board_color         = "#FFFFFF";
const light_color             = "#FFDEAD";
const green_color             = "#008000";
const red_color               = "#FF0000";

const main_dot_color          = "#1E90FF";
const complementary_dot_color = "";

const mehen_square_color_list = [
    [0, 7, out_board_color],
    [0, 6, out_board_color],
    [0, 5, out_board_color],
    [0, 4, out_board_color],
    [0, 3, out_board_color],
    [0, 2, out_board_color],
    [0, 1, out_board_color],
    [0, 0, out_board_color],
    [1, 7, light_color],
    [1, 6, light_color],
    [1, 5, light_color],
    [1, 4, red_color],
    [1, 3, light_color],
    [1, 2, green_color],
    [1, 1, light_color],
    [1, 0, light_color],
    [2, 0, light_color],
    [3, 0, light_color],
    [4, 0, light_color],
    [5, 0, green_color],
    [6, 0, light_color],
    [7, 0, light_color],
    [8, 0, light_color],
    [8, 1, light_color],
    [8, 2, light_color],
    [8, 3, green_color],
    [8, 4, light_color],
    [8, 5, light_color],
    [8, 6, light_color],
    [8, 7, red_color],
    [7, 7, light_color],
    [6, 7, green_color],
    [5, 7, light_color],
    [4, 7, light_color],
    [3, 7, light_color],
    [2, 7, green_color],
    [2, 6, light_color],
    [2, 5, light_color],
    [2, 4, light_color],
    [2, 3, light_color],
    [2, 2, light_color],
    [2, 1, green_color],
    [3, 1, light_color],
    [4, 1, green_color],
    [5, 1, light_color],
    [6, 1, light_color],
    [7, 1, light_color],
    [7, 2, light_color],
    [7, 3, light_color],
    [7, 4, green_color],
    [7, 5, light_color],
    [7, 6, light_color],
    [6, 6, light_color],
    [5, 6, green_color],
    [4, 6, light_color],
    [3, 6, green_color],
    [3, 5, light_color],
    [3, 4, light_color],
    [3, 3, light_color],
    [3, 2, green_color],
    [4, 2, light_color],
    [5, 2, green_color],
    [6, 2, light_color],
    [6, 3, light_color],
    [6, 4, light_color],
    [6, 5, green_color],
    [5, 5, light_color],
    [4, 5, green_color],
    [4, 4, light_color],
    [4, 3, green_color],
    [5, 3, light_color],
    [5, 4, green_color],
    [9, 0, out_board_color],
    [9, 1, out_board_color],
    [9, 2, out_board_color],
    [9, 3, out_board_color],
    [9, 4, out_board_color],
    [9, 5, out_board_color],
    [9, 6, out_board_color],
    [9, 7, out_board_color],
];
